spring.application.name=tasks
server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!

spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servelet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE